## @file
# WOA-Spacewar - Nothing Phone (1) Firmware Volume Include
# Copyright (c) 2026 aliss32 - GPL-3.0-or-later
##

FILE FREEFORM = 7E374E25-8E01-4FEE-87F2-390C23C606CD {
    SECTION RAW = Platform/Nothing/sm7325/AcpiTables/DSDT.aml
    SECTION RAW = Silicon/Qualcomm/sm7325/AcpiTables/BuiltIn/APIC.aml
    SECTION RAW = Silicon/Qualcomm/sm7325/AcpiTables/BuiltIn/BGRT.aml
    SECTION RAW = Silicon/Qualcomm/sm7325/AcpiTables/BuiltIn/DBG2.aml
    SECTION RAW = Silicon/Qualcomm/sm7325/AcpiTables/BuiltIn/FACP.aml
    SECTION RAW = Silicon/Qualcomm/sm7325/AcpiTables/BuiltIn/FACS.aml
    SECTION RAW = Silicon/Qualcomm/sm7325/AcpiTables/BuiltIn/GTDT.aml
    SECTION RAW = Silicon/Qualcomm/sm7325/AcpiTables/BuiltIn/IORT.aml
    SECTION RAW = Silicon/Qualcomm/sm7325/AcpiTables/BuiltIn/MADT.aml
    SECTION RAW = Silicon/Qualcomm/sm7325/AcpiTables/BuiltIn/MCFG.aml
    SECTION RAW = Silicon/Qualcomm/sm7325/AcpiTables/BuiltIn/PPTT.aml
    SECTION RAW = Silicon/Qualcomm/sm7325/AcpiTables/BuiltIn/SRAT.aml
    SECTION RAW = Silicon/Qualcomm/sm7325/AcpiTables/BuiltIn/SSDT.aml
    SECTION RAW = Silicon/Qualcomm/sm7325/AcpiTables/BuiltIn/TPM2.aml
}
