#!/usr/bin/env python3
"""
WOA-Spacewar — Driver Adaptation Script
=========================================
Takes the working Lisa (Xiaomi 11 Lite NE / SM7325) driver pack
and adds Spacewar (Nothing Phone 1 / SM7325-AE) Device IDs.

Since both devices share the same Snapdragon 778G SoC family,
most drivers are compatible with minor Device ID additions.

Source driver pack:
  AistopGit/windows_oem_xiaomi_lisa
  (Originally from WOA-Project/Qualcomm-Reference-Drivers)

Credits:
  - AistopGit       — windows_oem_xiaomi_lisa driver pack
  - N1kroks         — Lisa port, experimental GPU driver (v2523.12)
  - gus33000        — WOA architecture and driver expertise
  - WOA-Project     — Qualcomm reference drivers
  - edk2-porting    — WOA-Drivers base

AI-assisted: Claude (Anthropic) — claude.ai
Copyright (c) 2026 aliss32 — GPL-3.0-or-later

NOTE: Device IDs marked [TODO] will be updated after hardware_report.json
      is generated by analyze_hardware.py (GitHub Actions → analyze.yml).
"""

import os
import re
import json
import shutil
import argparse


# ── Spacewar Device IDs ───────────────────────────────────────────────────────
# Sources:
#   - [CONFIRMED] QCA6750 from BoardConfig.mk wlan.ko alias
#   - [CONFIRMED] WCD9385 from SM7325 platform standard
#   - [TODO]      Touch and FP IDs pending hardware_report.json

SPACEWAR_DEVICE_IDS = {

    "GPU": {
        # Adreno 642L — SM7325-AE
        # Lisa GPU driver works because same Adreno 642L GPU
        # Credits: AistopGit for the experimental GPU driver
        "ids": [
            "QCOM\\VID_17CB&PID_06A6&REV_0200",
            "QCOM\\VID_17CB&PID_06A6",
        ],
        "description": "Qualcomm Adreno 642L Graphics — Nothing Phone (1)",
        "source": "Lisa v2523.12 experimental GPU driver",
        "confirmed": True,
    },

    "WiFi": {
        # [CONFIRMED] QCA6750 from BoardConfig.mk
        # wlan.ko:qca_cld3_qca6750.ko
        "ids": [
            "QCOM\\VID_17CB&PID_1103",
        ],
        "description": "Qualcomm QCA6750 Wi-Fi 6E — Nothing Phone (1)",
        "source": "BoardConfig.mk (confirmed)",
        "confirmed": True,
    },

    "Bluetooth": {
        # Paired with QCA6750
        "ids": [
            "QCOM\\VID_17CB&PID_1104",
        ],
        "description": "Qualcomm Bluetooth 5.2 — Nothing Phone (1)",
        "source": "QCA6750 BT companion",
        "confirmed": True,
    },

    "UFS": {
        # UFS 3.1 controller — same on all SM7325 devices
        "ids": [
            "QCOM\\VID_17CB&PID_0240",
        ],
        "description": "Qualcomm UFS 3.1 — Nothing Phone (1)",
        "source": "SM7325 platform standard",
        "confirmed": True,
    },

    "PMIC": {
        # PM7325 — confirmed from Android DT
        "ids": [
            "QCOM\\VID_17CB&PID_0C57",
        ],
        "description": "Qualcomm PM7325 PMIC — Nothing Phone (1)",
        "source": "Android DT (confirmed)",
        "confirmed": True,
    },

    "Audio": {
        # WCD9385 — SM7325 standard audio codec
        "ids": [
            "QCOM\\VID_17CB&PID_0B27",
        ],
        "description": "Qualcomm WCD9385 Audio Codec — Nothing Phone (1)",
        "source": "SM7325 platform standard",
        "confirmed": True,
    },

    "Sensors": {
        # Sensor hub — SM7325 standard
        # Lisa v2523.12 sensor drivers used
        "ids": [
            "QCOM\\VID_17CB&PID_0C6B",
        ],
        "description": "Qualcomm Sensor Hub — Nothing Phone (1)",
        "source": "Lisa v2523.12 experimental sensor driver",
        "confirmed": True,
    },

    "Touch": {
        # [TODO] IC model unknown — will be confirmed after analyze.yml
        "ids": [
            "TODO_TOUCH_DEVICE_ID",
        ],
        "description": "Touchscreen — Nothing Phone (1)",
        "source": "TODO — run analyze.yml first",
        "confirmed": False,
    },

    "Fingerprint": {
        # [TODO] Under-display optical IC unknown
        "ids": [
            "TODO_FP_DEVICE_ID",
        ],
        "description": "Under-display Optical Fingerprint — Nothing Phone (1)",
        "source": "TODO — run analyze.yml first",
        "confirmed": False,
    },
}


# ── INF Patcher ───────────────────────────────────────────────────────────────

def patch_inf(filepath, driver_type):
    entry = SPACEWAR_DEVICE_IDS.get(driver_type)
    if not entry:
        return False
    if not entry["confirmed"]:
        print(f"  ⏳ {driver_type}: skipped (TODO — needs hardware analysis)")
        return False

    content = read_file(filepath)
    changed = False

    for hw_id in entry["ids"]:
        if hw_id in content or hw_id == "TODO_TOUCH_DEVICE_ID" or hw_id == "TODO_FP_DEVICE_ID":
            continue

        # Insert before [Strings] section
        inject = (
            f"\n; Spacewar (Nothing Phone 1) — {entry['description']}\n"
            f"; Source: {entry['source']}\n"
            f"%DeviceDesc% = Install, {hw_id}\n"
        )
        content = re.sub(r'(\[Strings\])', inject + r'\1', content, count=1)
        changed = True

    if changed:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"  ✅ {driver_type}: patched {os.path.basename(filepath)}")

    return changed


def read_file(path):
    try:
        with open(path, 'r', encoding='utf-8', errors='ignore') as f:
            return f.read()
    except Exception:
        return ""


# ── Keyword mapping: filename → driver type ───────────────────────────────────

INF_KEYWORDS = {
    "gpu":         "GPU",
    "adreno":      "GPU",
    "display":     "GPU",
    "wifi":        "WiFi",
    "wlan":        "WiFi",
    "qca":         "WiFi",
    "bt":          "Bluetooth",
    "bluetooth":   "Bluetooth",
    "ufs":         "UFS",
    "storage":     "UFS",
    "pmic":        "PMIC",
    "pm73":        "PMIC",
    "audio":       "Audio",
    "wcd":         "Audio",
    "codec":       "Audio",
    "sensor":      "Sensors",
    "imu":         "Sensors",
    "touch":       "Touch",
    "fingerprint": "Fingerprint",
    "fp":          "Fingerprint",
}


# ── Main ──────────────────────────────────────────────────────────────────────

def adapt_drivers(source_path, output_path):
    print("\n🔧 WOA-Spacewar Driver Adaptation")
    print("=" * 45)
    print(f"   Source : {source_path}")
    print(f"   Output : {output_path}\n")

    # Copy Lisa drivers to output
    if os.path.exists(output_path):
        shutil.rmtree(output_path)
    shutil.copytree(source_path, output_path)
    print(f"✅ Copied Lisa driver pack to {output_path}\n")

    updated = skipped = todo = 0

    for root, _, files in os.walk(output_path):
        for filename in files:
            if not filename.lower().endswith('.inf'):
                continue

            filepath = os.path.join(root, filename)
            name_lower = filename.lower()

            driver_type = None
            for kw, dtype in INF_KEYWORDS.items():
                if kw in name_lower:
                    driver_type = dtype
                    break

            if not driver_type:
                continue

            entry = SPACEWAR_DEVICE_IDS.get(driver_type, {})
            if not entry.get("confirmed", False):
                todo += 1
                continue

            result = patch_inf(filepath, driver_type)
            if result:
                updated += 1
            else:
                skipped += 1

    print(f"\n{'='*45}")
    print(f"  ✅ Patched : {updated} files")
    print(f"  ⏭️  Skipped : {skipped} files (already patched)")
    print(f"  ⏳ TODO    : {todo} files (need hardware analysis)")
    print(f"{'='*45}")
    print("\nNext step: Run analyze.yml → then re-run this script")
    print("           to patch Touch and Fingerprint drivers.\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("source", help="Lisa driver pack path")
    parser.add_argument("output", help="Output path for Spacewar drivers")
    args = parser.parse_args()
    adapt_drivers(args.source, args.output)


if __name__ == "__main__":
    main()
